import Navbar from "@/components/Navbar";
import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import AuthProvider from "./AuthProvider";
import { options } from "./api/auth/[...nextauth]/options";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(options);

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <MantineProvider>
            <Navbar session={session} />
            <main className="p-4">{children}</main>
            <footer>footer</footer>
          </MantineProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
